<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <img alt="logo mysql" src="/db/image/mysql" width="45" height="30" class="d-inline-block align-top">
        Admin
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Opérations
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<?= $this->url('db/index', ['controller'=>'db/index','action'=>'initdatabase']) ?>">Construire la base </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="<?= $this->url('db/client', ['action'=>'create']) ?>">Create Client</a>
                    <a class="dropdown-item" href="<?= $this->url('db/client', ['action'=>'drop']) ?>">Drop Client</a>
                    <a class="dropdown-item" href="<?= $this->url('db/client', ['action'=>'insert']) ?>">Insert Client</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<!--
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">

            <a class="navbar-brand" href="/">
                <img alt="logo mysql" src="/db/image/mysql">
            </a>
            <a class="navbar-brand" href="<?= $this->url('db/index', ['controller'=>'db/index','action'=>'initdatabase']) ?>">Construire la base </a>

        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Table <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url('db/client', ['action'=>'create']) ?>">Create Client</a></li>
                        <li><a href="<?= $this->url('db/client', ['action'=>'drop']) ?>">Drop Client</a></li>
                        <li><a href="<?= $this->url('db/client', ['action'=>'insert']) ?>">Insert Client</a></li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
-->