<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">

            <a class="navbar-brand" href="/">
                <!--<img alt="Brand" src="/db/images/SQLite-logo.png">-->
            </a>
            <a class="navbar-brand" href="<?= $this->url('db/index', ['controller'=>'db/index','action'=>'initdatabase']) ?>">Construire la base </a>

        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Table <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url('db/client', ['action'=>'create']) ?>">Create Client</a></li>
                        <li><a href="<?= $this->url('db/client', ['action'=>'drop']) ?>">Drop Client</a></li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>