<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\View\Helper\Form $viewFormHelper
 * @var \Zend\Form\View\Helper\FormElement $viewFormElementHelper
 * @var \Zend\Form\Element\Color $inputCouleur
 * @var \Zend\Form\Element\Button $inputSubmit
 */
$form = $this->form;
$viewFormHelper = $this->form();
$viewFormElementHelper = $this->formElement();
$inputCouleur = $form->get('couleur');
$inputSubmit = $form->get('submit');

$inputSubmit->setAttribute('class',"btn btn-primary");
$form->prepare();

$bgColor = ( isset($this->bgColor) ? $this->bgColor : '#F5F5F5');
?>
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="border: solid 3px #dddddd; background-color: <?= $bgColor ?>; padding: 5px">
            <div class="container">
            <?= $viewFormHelper->openTag($form) ?>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label"><?= $inputCouleur->getLabel() ?></label>
                    <div class="col-sm-10"><?= $viewFormElementHelper->render($inputCouleur) ?></div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10"><?= $viewFormElementHelper->render($inputSubmit) ?></div>
                </div>
            <?= $viewFormHelper->closeTag() ?>
            </div>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>